### ISSUE TITLE
compute_view not working

### ISSUE THREAD

**Issue by giswqs** [developmentseed/lonboard#365] opened 2024-02-14 13:52 UTC
## Context
I am trying to use to the `compute_view` method to get the latitude, longitude, and zoom level of the layer so that the map can automatically zoom to the area of interest. It used to work, but not any more. It throws the following error:

> AttributeError: 'pyarrow.lib.ChunkedArray' object has no attribute '_bbox'

## Code

```python
import geopandas as gpd
from lonboard import Map, SolidPolygonLayer
from lonboard._viewport import compute_view

gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

layer = SolidPolygonLayer.from_geopandas(
    gdf,
    get_fill_color=[255, 0, 0],
)

compute_view(layer.table)
```

## Error
![image](https://github.com/developmentseed/lonboard/assets/5016453/3fc314e4-c9f7-4eab-9534-244205bfc5e8)

**Comment by giswqs** [comment] 2024-02-14 15:41
Understood. What is the recommended way of getting the center and zoom level of a layer so that the map can zoom to the layer programmatically?

**Comment by kylebarron** [comment] 2024-02-14 17:48
The simple answer is that there isn't a public API for this because lonboard expects to be able to auto-center once when the user creates a map. We don't try to support auto-zooming for new layers because that's an open question: to what extent should it zoom to the new layer, even if it's at a completely different location than the previous layer. 

We have some _heuristics_ internally, but those heuristics are not stable enough to be exposed publicly IMO.

The `table` attribute of any layer that subclasses from `BaseArrowLayer` is public; that will always be a GeoArrow table object. For the forseeable future that will always be a `pyarrow.Table`. You can rely on those public attributes

**Comment by kylebarron** [comment] 2024-02-29 20:29
I'm going to close this because this is expected behavior. At some point in the future, maybe 
more internals will be made public, but for now I'm focusing on the stability of the end-user

**Closed by kylebarron** 2024-02-29 20:29 UTC
