### ISSUE TITLE
Support for rendering inside VSCode

### ISSUE THREAD

**Issue by jc9677** [developmentseed/lonboard#156] opened 2023-10-27 18:17 UTC
Hi, I'm really looking forward to playing with lonboard but I can't get viz to to render. I've tried the two example notebooks... They render in your Binder and Colab links, but when I try them in local Jupyter, nothing gets displayed but a blank white bar in the cell output. The objects returned from viz seem valid -- I can see coordinates etc when I print them as a string. I assume there might be a widget support issue or something like that. I'm using conda to create env's on a Windows machine. Tried various python 3 versions, tried upgrading/downgrading Jupyter-related packages but no luck so far.  Also tried upgrading & downgrading pyogrio, lonboard, pyarrow...

**Comment by kylebarron** [comment] 2023-10-27 18:48
You could look for errors in the browser console (right click and choose `inspect` to open). Alternatively it could be an issue in your Python-jupyter environment setup. You should also try reloading the page, not just the jupyter kernel, if you haven't done that yet.

**Comment by jc9677** [comment] 2023-10-27 21:00
The Jupyter logs below are from the cell in question in north-america-roads.ipynb
(`map_ = viz(gdf.geometry, width_min_pixels=0.8)`
`map_
`). 

Unfortunately I don't know how to trace the cause. Hoping something stands out for you.


> 16:41:30.200 [info] Handle Execution of Cells 14 for ~\LONBOARD\north-america-roads.ipynb
> 16:41:30.203 [info] Kernel acknowledged execution of cell 14 @ 1698439290202
> 16:41:30.499 [info] End cell 14 execution @ 1698439290327, started @ 1698439290202, elapsed time = 0.125s
> 16:41:30.970 [info] [32mFetch Script for {"moduleName":"anywidget","moduleVersion":"0.6.5","requestId":"anywidget:0.6.5:1698439290969"}
> 16:41:30.970 [info] [32mFetch Script for anywidget
> 16:41:30.970 [info] [32mSearching for Widget Script anywidget#0.6.5 using cdns jsdelivr.com unpkg.com
> 16:41:31.116 [info] [32mWidget Script anywidget#0.6.5 found at URI: https://cdn.jsdelivr.net/npm/anywidget@0.6.5/dist/index.js
> 16:41:31.117 [info] Script source for Widget anywidget@0.6.5 was found from source cdn
> 16:41:31.117 [info] [32mScript for anywidget, is https://cdn.jsdelivr.net/npm/anywidget@0.6.5/dist/index.js from cdn
> 16:41:31.126 [warn] Failed to extract require.config from widget for anywidget from ~\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\temp\scripts\e13283a2642f4b869dfd0df99572879ed545f813d17b35b964886c57b19f89d5\jupyter\nbextensions\anywidget\extension.js
> 16:41:31.134 [info] [32mFetch Script for anywidget
> 16:41:31.134 [info] Script source for Widget anywidget@0.6.5 was found from source cdn
> 16:41:31.134 [info] [32mScript for anywidget, is https://cdn.jsdelivr.net/npm/anywidget@0.6.5/dist/index.js from cdn
> 16:41:31.235 [error] **Widget Error: Error: Failed to render widget b4cf712541304e54b473db411c1906c3, TypeError: Cannot read properties of undefined (reading 'widget_manager')**

**When I run the cell a second time:**

> 16:42:49.007 [info] Handle Execution of Cells 14 for ~\LONBOARD\north-america-roads.ipynb
> 16:42:49.038 [info] Kernel acknowledged execution of cell 14 @ 1698439369035
> 16:42:49.099 [error] Widget load failure {} {
>   className: 'LayoutModel',
>   moduleName: '@jupyter-widgets/base',
>   moduleVersion: '2.0.0',
>   cdnsUsed: false,
>   isOnline: true,
>   timedout: false,
>   error: '{}'
> }
> 16:42:49.315 [info] End cell 14 execution @ 1698439369135, started @ 1698439369035, elapsed time = 0.1s
> 16:42:49.923 [error] Widget Error: Error: Failed to render widget ecabd564fb5149948f0fe848c57b0714, TypeError: Cannot read properties of undefined (reading 'widget_manager')
> `

**Comment by kylebarron** [comment] 2023-10-27 21:06
> 16:41:31.126 [warn] Failed to extract require.config from widget for anywidget from ~.vscode-insiders\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\temp\scripts\e13283a2642f4b869dfd0df99572879ed545f813d17b35b964886c57b19f89d5\jupyter\nbextensions\anywidget\extension.js

You're not in Jupyter, you're in VSCode. VSCode is not currently supported

**Comment by jc9677** [comment] 2023-10-27 21:52
Sorry, I had initially mentioned VS Code while drafting the issue but I reworded things and forgot to put it back in. I did try Jupyter in a dedicated env (not tied to VS Code in any way) and couldn't render there either but that must have been a different problem. I will give it another go outside of VS Code. Thanks Kyle!

**Comment by manzt** [comment] 2023-11-06 16:52
anywidget should work in VSCode environments. If i get the chance, i can dig into the devtools to try to see what's going on

**Comment by kylebarron** [comment] 2023-11-06 17:12
Actually it looks like it's fixed on main, so it was probably fixed by https://github.com/developmentseed/lonboard/pull/199

<img width="842" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/e852c915-2375-4f93-8f42-adba645a06d9">

<img width="1248" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/475e90d0-85cb-4264-bf2a-b4a099994120">

**Comment by kylebarron** [comment] 2023-11-06 17:17
Yep, I can confirm this was fixed by https://github.com/developmentseed/lonboard/pull/199. If I rewind before that commit, I get the following error, which is the same as what was described in https://github.com/manzt/anywidget/issues/369.

<img width="337" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/a1a87ad9-8ab6-4632-a1c0-f3343362d7cf">

I'll make a new release sometime this week

**Closed by kylebarron** 2023-11-06 17:17 UTC

**Comment by robmarkcole** [comment] 2024-10-29 10:29
I've discovered that lonboard plots don't render on Lightning.ai and reported it to them

**Comment by manzt** [comment] 2024-10-29 14:35
@robmarkcole you want to point them at [anywidget](https://anywidget.dev), which lonboard [and others](https://anywidget.dev/en/community/) rely on for compatibility with various notebook platforms.

**Comment by robmarkcole** [comment] 2024-10-29 14:57
Thanks for the info @manzt will pass it along
